"""Constants for the ElprisetJustNu integration."""
DOMAIN = "elprisetjustnu"
DEVICE_IDENTIFIER = "elprisetjustnu"
ATTR_EPJNED = "EPJNED"
CURRENT_PRICE = "current_price"
DAY_AVERAGE_PRICE = "day_average_price"
CURRENT_PRICE_AND_FEES = "current_price_and_fees"
DAY_AVERAGE_PRICE_AND_FEES = "day_average_price_and_fees"
DEFAULT_NAME = "ElprisetJustNu"
VAL_CURRENT_PRICE = "current_price"
VAL_DAY_AVERAGE_PRICE = "day_average_price"
API_URL = "https://www.elprisetjustnu.se"
UNIT_OF_M_PRICE = "SEK/kWh"
FEES = "fees"
DAY_PRICES = "day_prices"
